[build-system]
requires = [
  "setuptools>=68",
  "wheel",
  "cmake>=3.18",
  "ninja; platform_system!='Windows'",
  "packaging",
  # use --no-build-isolation
  "torch",
]
build-backend = "setuptools.build_meta"

[project]
name = "fasteq"
version = "0.1.0"
description = "FastEq CUDA extensions"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
package-dir = {"" = "faseq"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["faseq"]
