// !!! This is a file automatically generated by hipify!!!
#include <ATen/dtk_macros.h>
#pragma once

#include <cstdint>
#include <hip/hip_runtime.h>
#include <hip/hip_runtime.h>
#include <string>
#include <vector>

void mutipath_equi_linear_fwd_f32_impl(const uint32_t &num_paths,              // path nums
                                       float *out,                             // [B, total_i, V]
                                       float *x,                               // [B, total_i, U]
                                       float *w,                               // [num_paths, U, V]
                                       const uint32_t &B,                      // batch
                                       const uint32_t &total_i,                // total_i
                                       const std::vector<int64_t> &i_dims_vec, // i dims
                                       const uint32_t &U,                      // U
                                       const uint32_t &V,                      // V
                                       const std::vector<double> &cg_val_vec,  // cg_val
                                       const hipStream_t &cur_stream          // current stream
);

void mutipath_equi_linear_bwd_f32_impl(const uint32_t &out_num_paths,          // path nums
                                       float *out,                             // [B, out_total_i, U]
                                       float *grad,                            // [B, grad_total_i, V]
                                       float *w,                               // [OUT_NUM_PATHS, U, V]
                                       const uint32_t &B,                      // batch
                                       const uint32_t &out_total_i,            // out_total_i
                                       const std::vector<int64_t> &out_i_dims, // out i dims
                                       const uint32_t &U,                      // U
                                       const uint32_t &V,                      // V
                                       const std::vector<double> &cg_val_vec,  // cg_val
                                       const hipStream_t &cur_stream          // current stream
);

void mutipath_equi_linear_fwd_f64_impl(const uint32_t &num_paths,              // path nums
                                       double *out,                            // [B, total_i, V]
                                       double *x,                              // [B, total_i, U]
                                       double *w,                              // [num_paths, U, V]
                                       const uint32_t &B,                      // batch
                                       const uint32_t &total_i,                // total_i
                                       const std::vector<int64_t> &i_dims_vec, // i dims
                                       const uint32_t &U,                      // U
                                       const uint32_t &V,                      // V
                                       const std::vector<double> &cg_val_vec,  // cg_val
                                       const hipStream_t &cur_stream          // current stream
);
