// !!! This is a file automatically generated by hipify!!!
#include <ATen/dtk_macros.h>
#include "hip/hip_runtime.h"
#ifndef CUDA_UTILS_CUH
#define CUDA_UTILS_CUH

#ifdef __DTK_ARCH__
#define DEVICE __device__
#else
#define DEVICE
#endif

#ifndef WARP_SIZE
#define WARP_SIZE 32
#endif

#define CUDA_CHECK(ans) do { \
  hipError_t err = (ans); \
  if (err != hipSuccess) { \
    printf("CUDA Error: %s (%d) at %s:%d\n", hipGetErrorString(err), (int)err, __FILE__, __LINE__); \
  } \
} while(0)

template <typename T>
__device__ __forceinline__ T ld_g(const T* p) {
#if __DTK_ARCH__ >= 350
  return __ldg(p);
#else
  return *p;
#endif
}

template <typename T>
__device__ __forceinline__ T warp_reduce_sum(T v, unsigned mask) {
    #pragma unroll
    for (int offset = 16; offset > 0; offset >>= 1) {
        v += __shfl_down_sync(mask, v, offset);
    }
    return v;
}

template <typename T>
__device__ __forceinline__ T warp_reduce_sum(T v) {
  unsigned mask = 0xffffffffu;
  #pragma unroll
  for (int off = 16; off > 0; off >>= 1)
    v += __shfl_down_sync(mask, v, off);
  return v;
}

template <typename T>
__device__ __forceinline__ T warp_sum(T v) {
    unsigned mask = 0xffffffffu;
    #pragma unroll
    for (int d = 16; d > 0; d >>= 1) v += __shfl_down_sync(mask, v, d);
    return v;
}

template <typename T>
__device__ __forceinline__ T warp_sum_xor(T v) {
    #pragma unroll
    for (int mask = 16; mask > 0; mask >>= 1) {
        v += __shfl_xor_sync(0xffffffff, v, mask);
    }
    return v;
}

__device__ __forceinline__ int shfl_i32(int v, int src_lane=0) {
    return __shfl_sync(0xffffffff, v, src_lane);
}

__device__ __forceinline__ int shfl_lane0_i32(int v) {
  return __shfl_sync(0xffffffffu, v, 0);
}

// block-reduce scalar across warps using shared buffer (size >= num_warps)
template <typename AccT>
__device__ __forceinline__ AccT block_reduce_sum_scalar(AccT v, AccT* __restrict__ sh_warp) {
  int lane = threadIdx.x & 31;
  int warp = threadIdx.x >> 5;
  int num_warps = (blockDim.x + 31) >> 5;

  v = warp_reduce_sum(v);
  if (lane == 0) sh_warp[warp] = v;
  __syncthreads();

  AccT sum = (AccT)0;
  if (warp == 0) {
    sum = (lane < num_warps) ? sh_warp[lane] : (AccT)0;
    sum = warp_reduce_sum(sum);
  }
  __syncthreads();
  // broadcast from lane0 of warp0
  return __shfl_sync(0xffffffffu, sum, 0);
}


// ---------------------------------------------
// cp.async helpers (SM80+)
// ---------------------------------------------
#if defined(__DTK_ARCH__) && (__DTK_ARCH__ >= 800)

__device__ __forceinline__ void cp_async_ca_16B(void* smem_dst, const void* gmem_src) {
    // cp.async expects shared address in 32-bit "shared space" address
    unsigned int smem_u32 = static_cast<unsigned int>(__cvta_generic_to_shared(smem_dst));
    asm volatile(
        "cp.async.ca.shared.global [%0], [%1], 16;\n" ::  // 16 bytes
        "r"(smem_u32), "l"(gmem_src)
    );
}


__device__ __forceinline__ void cp_async_cg_16B(void* smem_dst, const void* gmem_src) {
    // cp.async expects shared address in 32-bit "shared space" address
    unsigned int smem_u32 = static_cast<unsigned int>(__cvta_generic_to_shared(smem_dst));
    asm volatile(
        "cp.async.cg.shared.global [%0], [%1], 16;\n" ::  // 16 bytes
        "r"(smem_u32), "l"(gmem_src)
    );
}

__device__ __forceinline__ void cp_async_commit_group() {
    asm volatile("cp.async.commit_group;\n" ::);
}

template<int N>
__device__ __forceinline__ void cp_async_wait_group() {
  asm volatile("cp.async.wait_group %0;\n" :: "n"(N));
}

__device__ __forceinline__ void cp_async_wait_group0() {
    asm volatile("cp.async.wait_group 0;\n" ::);
}

#endif



template <typename T>
__device__ __forceinline__ void stage_gmem_to_smem_cpasync_16B(
    T* __restrict__ smem,
    const T* __restrict__ gmem,
    int n_elems
) {
#if defined(__DTK_ARCH__) && (__DTK_ARCH__ >= 800)
    // choose a 16B vector type
    using Vec = std::conditional_t<std::is_same<T, float>::value, float4, double2>;
    constexpr int VEC_ELEMS = (int)(sizeof(Vec) / sizeof(T)); // float:4, double:2

    // n_elems should be multiple of VEC_ELEMS for fast path
    int n_vec = n_elems / VEC_ELEMS;

    int tid = threadIdx.x;
    int threads = blockDim.x;

    Vec* __restrict__ smem_v = reinterpret_cast<Vec*>(smem);
    const Vec* __restrict__ gmem_v = reinterpret_cast<const Vec*>(gmem);

    // issue cp.async (16B) per thread
    #pragma unroll 1
    for (int i = tid; i < n_vec; i += threads) {
        cp_async_ca_16B((void*)&smem_v[i], (const void*)&gmem_v[i]);
    }

    // finalize: commit + wait + sync
    cp_async_commit_group();
    cp_async_wait_group0();
#else
    // fallback (shouldn't hit on H100)
    int tid = threadIdx.x;
    int threads = blockDim.x;
    #pragma unroll 1
    for (int i = tid; i < n_elems; i += threads) {
        smem[i] = gmem[i];
    }
#endif
}


DEVICE inline int find_integer_divisor(int x, int bdim) {
  return (x + bdim - 1) / bdim;
}

DEVICE inline int ceil_div(int x, int bdim) {
  return (x + bdim - 1) / bdim;
}

template <class T>
DEVICE inline T *shared_array(unsigned int n_elements, void *&ptr,
                              unsigned int *space) noexcept {
  const unsigned long long inptr = reinterpret_cast<unsigned long long>(ptr);
  const unsigned long long end = inptr + n_elements * sizeof(T);
  if (space)
    *space += static_cast<unsigned int>(end - inptr);
  ptr = reinterpret_cast<void *>(end);
  return reinterpret_cast<T *>(inptr);
}

static inline int ceil_div_int(int a, int b) { return (a + b - 1) / b; }

template <typename T>
__device__ __forceinline__ T fma_acc(T a, T b, T c) {
    // default: fallback (for e.g. half/bfloat16 you might want custom)
    return a * b + c;
}

template <>
__device__ __forceinline__ float fma_acc<float>(float a, float b, float c) {
    return fmaf(a, b, c);
}

template <>
__device__ __forceinline__ double fma_acc<double>(double a, double b, double c) {
    return fma(a, b, c);
}

struct PathMeta {
  int i;
  int j;
  int k;
  int v;
  float coeff;
};

template <typename scalar_t>
__device__ __forceinline__ scalar_t load_vec_u(const char* base, int byte_off, int lane) {
    return *(reinterpret_cast<const scalar_t*>(base + byte_off) + lane);
}

template <typename scalar_t>
__device__ __forceinline__ scalar_t load_scalar(const char* base, int byte_off) {
    return *reinterpret_cast<const scalar_t*>(base + byte_off);
}


/*
// forward declare multiple types...
template float *shared_array<float>(unsigned int n_elements, void *&ptr,
                                    unsigned int *space) noexcept;
template double *shared_array<double>(unsigned int n_elements, void *&ptr,
                                      unsigned int *space) noexcept;
template int *shared_array<int>(unsigned int n_elements, void *&ptr,
                                unsigned int *space) noexcept;
template short *shared_array<short>(unsigned int n_elements, void *&ptr,
                                    unsigned int *space) noexcept; */

#endif // CUDA_UTILS_CUH